---
- name: Template for Creating Rule Set for AlertManager
  hosts: all
  become: true
  gather_facts: true
  tasks:
  - name: Create AlertManager Rule Set for Grafana Service State
    template:
      src: /etc/ansible/templates/service_state_alert_rule.conf.j2
      dest: /etc/prometheus/service_state_rules.yml
    delegate_to: infra-prometheus-01
    ignore_errors: true

  - name: Reload Config for Prometheus Service
    ansible.builtin.systemd:
      state: restarted
      name: prometheus
    when:
      - ansible_facts['hostname'] == 'infra-prometheus-01'

  - name: Reload Config for AlertManager Service
    ansible.builtin.systemd:
      state: restarted
      name: alertmanager
    when:
      - ansible_facts['hostname'] == 'infra-prometheus-01'